/*
 * Copyright (C) 2010 SonarSource SA
 * All rights reserved
 * mailto:contact AT sonarsource DOT com
 */
package com.sonarsource.sslr.api;

/**
 * The AstVisitor allows to visit some desired AstNode. The AstAndTokenVisitor extends this first interface to add a new feature : being
 * visited for each Token generated by the Lexer.
 * 
 */
public interface AstAndTokenVisitor extends AstVisitor {

  /**
   * Called sequentially for each token generated by the Lexer
   * 
   * @param token
   *          Token to visit
   */
  void visitToken(Token token);
}
