name: sonar-release
# This workflow is triggered manually with the full release version.
on:
  workflow_dispatch:
    inputs:
      version:
        description: Full version including build number, e.g. 1.25.1.3886
        required: true
        type: string

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v7
    with:
      version: ${{ inputs.version }}
      publishToBinaries: false
      mavenCentralSync: true
      slackChannel: squad-corelang-releases
